---

version: "3.7"

services:
  minio:
    image: minio/minio
    command: server /export
    ports:
      - 9000:9000
    volumes:
      - ./s3-clone:/export
    environment:
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_ACCESS_KEY_OLD: minioadmin
      MINIO_SECRET_KEY_OLD: minioadmin
    networks:
      - container-link
  minio-initializer:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minio_access minio_secret) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/sunacket;
      /usr/bin/mc policy download myminio/sunacket;
      exit 0;
      "
    networks:
      - container-link
