---

version: "3.7"

services:
  aggregation-fluentd:
    image: sunakan/suna-aggregation-fluentd:latest
    ports:
      - ${AGGREGATION_FLUENTD_PORT}:${AGGREGATION_FLUENTD_PORT}
    environment:
      FLUENTD_PORT: ${AGGREGATION_FLUENTD_PORT}
      FLUENTD_S3_BUCKET: sunacket
      FLUENTD_S3_REGION: ap-northeast-1
      FLUENTD_S3_ENDPOINT: http://minio:9000/
      FLUENTD_S3_ACCESS_KEY: minio_access
      FLUENTD_S3_SECRET_KEY: minio_secret
    networks:
      - container-link
