check:
	aws sts get-caller-identity
	aws --profile shared sts get-caller-identity
	aws --profile development sts get-caller-identity
	aws --profile sandbox sts get-caller-identity
	aws --profile iac sts get-caller-identity
