export DOCKER_SUNATRA_REPOSITORY=sunakan/sunatra
export DOCKER_RUBY_TAG=2.7-slim
export DOCKER_NGINX_REPOSITORY=sunakan/suna-nginx-sidecar
export DOCKER_NGINX_TAG=stable
export DOCKER_FLUENTD_REPOSITORY=sunakan/suna-fluentd-sidecar
export DOCKER_FLUENTD_TAG=v1.8-1

build-sunatra:
	bash build-sunatra.sh

build-nginx:
	bash build-nginx.sh

build-fluentd:
	bash build-fluentd.sh
