---

version: "3.7"

services:
  fake-app:
    command: ["bash", "/app.sh"]
    image: debian:buster-slim
    volumes:
      - ./fake-app.sh:/app.sh
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:${FLUENTD_PORT}"
        tag: "s3-clone.{{.Name}}"
        fluentd-async-connect: "true"
    depends_on:
      - fluentd
  fluentd:
    image: sunakan/suna-aggregation-fluentd
    ports:
      - ${FLUENTD_PORT}:${FLUENTD_PORT}
    volumes:
      - ../aggregation-fluentd/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      FLUENTD_PORT: ${FLUENTD_PORT}
      FLUENTD_S3_BUCKET: sunacket
      FLUENTD_S3_REGION: ap-northeast-1
      FLUENTD_S3_ENDPOINT: http://minio:9000/
      FLUENTD_S3_ACCESS_KEY: minio_access
      FLUENTD_S3_SECRET_KEY: minio_secret
    depends_on:
      - minio
  minio:
    image: minio/minio
    command: server /export
    ports:
      - 9000:9000
    volumes:
      - ./s3-clone:/export
    environment:
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
      MINIO_ACCESS_KEY_OLD: minioadmin
      MINIO_SECRET_KEY_OLD: minioadmin
  minio-initializer:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minio_access minio_secret) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/sunacket;
      /usr/bin/mc policy download myminio/sunacket;
      exit 0;
      "
