---

version: "3.7"

services:
  app:
    container_name: sunatra
    image: sunakan/sunatra:latest
    volumes:
      - ./sunatra:/app
    environment:
      SINATRA_PORT: ${SINATRA_PORT}
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:${FLUENTD_PORT}"
        # ImageName=sunakan/sunatra:latest.コンテナ名.コンテナIDが
        tag: "container-log.app.{{.ImageName}}.{{.Name}}.{{.ID}}"
        fluentd-async-connect: "true"
    depends_on:
      - fluentd
  nginx:
    container_name: nginx
    image: sunakan/suna-nginx-sidecar:latest
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      NGINX_PORT: ${NGINX_PORT}
      NGINX_LOCATION: suna-app
      APP_HOST: app
      APP_PORT: ${SINATRA_PORT}
      HEALTHCHECK_PATH: /health_check
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:${FLUENTD_PORT}"
        tag: "container-log.nginx.{{.ImageName}}.{{.Name}}.{{.ID}}"
        fluentd-async-connect: "true"
    depends_on:
      - app
      - fluentd
  fluentd:
    container_name: fluentd-sidecar
    image: sunakan/suna-fluentd-sidecar:latest
    ports:
      - ${FLUENTD_PORT}:${FLUENTD_PORT}
    environment:
      FLUENTD_PORT: ${FLUENTD_PORT}
      POD_LOG_PREFIX: ${POD_LOG_PREFIX}
      AGGREGATION_FLUENTD_HOST: fake-aggregation-fluentd
      AGGREGATION_FLUENTD_PORT: 24224
    volumes:
      - ./fluentd-sidecar/fluent.conf:/fluentd/etc/fluent.conf
    depends_on:
      - fake-aggregation-fluentd
  fake-aggregation-fluentd:
    container_name: fake-aggregation-fluentd
    image: fluentd:v1.8-1
    volumes:
      - ./fluent.stdout.conf:/fluentd/etc/fluent.conf
