---

version: "3.7"

services:
  app:
    container_name: sunatra
    image: sunakan/sunatra:latest
    volumes:
      - ./sunatra:/app
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: "app.{{.ImageName}}.{{.Name}}.{{.ID}}"
        fluentd-async-connect: "true"
    depends_on:
      - fluentd
  nginx:
    container_name: nginx
    image: sunakan/suna-nginx-sidecar:latest
    ports:
      - 80:80
    environment:
      NGINX_PORT: 80
      NGINX_LOCATION: suna-app
      APP_HOST: app
      APP_PORT: 4567
      HEALTHCHECK_PATH: /health_check
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        tag: "nginx.{{.ImageName}}.{{.Name}}.{{.ID}}"
        fluentd-async-connect: "true"
    depends_on:
      - app
      - fluentd
  fluentd:
    tty: true
    container_name: fluentd-sidecar
    image: sunakan/suna-fluentd-sidecar:latest
    ports:
      - 24224:24224
