---

version: "3.7"

services:
  app:
    container_name: sunatra
    image: sunakan/sunatra:latest
    volumes:
      - ./sunatra:/app
  nginx:
    container_name: nginx
    image: sunakan/suna-nginx-sidecar:latest
    ports:
      - 80:80
    environment:
      NGINX_PORT: 80
      NGINX_LOCATION: suna-app
      APP_HOST: app
      APP_PORT: 4567
      HEALTHCHECK_PATH: /health_check
